---
- hosts: all
  become: true
  become_method: sudo

  vars:
    domain: helloworld.com
  
  tasks:
    - name: Install some packages
      apt:
        pkg:
        - docker
        - zsh
        - htop
        - git
        update_cache: yes

    - name: Set authorized key for user root copying it from current user
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id.pub') }}"






    - name: "install nginx"
      apt:
       name: ['nginx']
       state: latest

    - name: "create www directory"
      file:
        path: /var/www/{{ domain }}
        state: directory
        mode: '0775'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: copy nginx site.conf
      template:
        src: site.conf.j2
        dest: /etc/nginx/sites-enabled/{{ domain }}
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted


