---
- hosts: all
  become: true
  become_method: sudo

  vars:
    domain: helloworld.com
  
  tasks:
    - name: Install some packages
      apt:
        pkg:
        - docker
        - zsh
        - htop
        - git
        - python3-virtualenv
        update_cache: yes

    - name: Install fastAPI into the specified (virtualenv)
      pip:
        name: 
          - fastapi
          - "uvicorn[standard]"
        virtualenv: /opt/test_venv

    - name: create app dir
      file:
        path: /opt/app
        state: directory

    - name: copy app files
      copy:
        src: app/main.py
        dest: /opt/app/main.py

    - name: install app systemd file
      copy:
        src: main_app.service
        dest: /etc/systemd/system/main_app.service

    - name: Make sure a service unit is running
      systemd:
        state: started
        name: main_app
        daemon_reload: yes

    - name: Set authorized key for user root copying it from current user
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id.pub') }}"

    - name: "install nginx"
      apt:
       name: ['nginx']
       state: latest

    - name: delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: copy nginx site.conf
      template:
        src: site.conf.j2
        dest: /etc/nginx/sites-enabled/{{ domain }}
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted


